services:
  # 配置初始化服务 - 在其他服务启动前验证配置
  config-init:
    build:
      context: .
      dockerfile: Dockerfile.config
    container_name: avalon-config
    volumes:
      - .:/app/config
    working_dir: /app/config
    environment:
      - DOMAIN=${DOMAIN:-your-domain.com}
      - SECRET_PATH=${SECRET_PATH:-avalon-secret-path}
    command: ["validate"]

  caddy:
    image: caddy:2-alpine
    container_name: avalon-caddy
    restart: unless-stopped
    network_mode: host
    dns:
      - 169.254.169.254
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      config-init:
        condition: service_completed_successfully
      v2ray:
        condition: service_started
    environment:
      - DOMAIN=${DOMAIN:-your-domain.com}
      - SECRET_PATH=${SECRET_PATH:-avalon-secret-path}

  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: avalon-v2ray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
    network_mode: host
    dns:
      - 169.254.169.254
    depends_on:
      config-init:
        condition: service_completed_successfully
    command: ["run", "-c", "/etc/v2ray/config.json"]

volumes:
  caddy_data:
  caddy_config:

