services:
  # ==================== Manager 服务 ====================
  # 配置生成服务 - 通过 'docker compose run manager' 手动调用
  # 或通过 Makefile 自动调用
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avalon-manager
    volumes:
      - .:/app/config             # 挂载项目目录
      - ./data:/app/config/data   # 持久化数据目录
    environment:
      - DOMAIN=${DOMAIN:-your-domain.com}
      - SECRET_PATH=${SECRET_PATH:-}  # 留空，由 manager 自动生成
      - ACME_STAGING=${ACME_STAGING:-0}  # 是否使用 Staging 环境
    env_file:
      - .env
    profiles:
      - tools  # 不会自动启动，需要手动运行

  # ==================== V2Ray 服务 ====================
  # 核心代理服务
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: avalon-v2ray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
    network_mode: host
    command: ["run", "-c", "/etc/v2ray/config.json"]

  # ==================== Caddy 服务 ====================
  # 反向代理和 TLS 证书管理
  caddy:
    image: caddy:2-alpine
    container_name: avalon-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv:ro
      - ./data/caddy/data:/data        # 持久化证书数据（本地目录）
      - ./data/caddy/config:/config    # 持久化配置（本地目录）
    depends_on:
      v2ray:
        condition: service_started
    environment:
      - DOMAIN=${DOMAIN:-your-domain.com}
